# Generated by Django 3.0.8 on 2020-07-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='display_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
