# Generated by Django 3.0.8 on 2020-08-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20200804_0158'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailymovie',
            name='one current record only',
        ),
        migrations.RenameField(
            model_name='dailymovie',
            old_name='current_selection',
            new_name='active_movie',
        ),
        migrations.AddConstraint(
            model_name='dailymovie',
            constraint=models.UniqueConstraint(condition=models.Q(active_movie=True), fields=('active_movie',), name='one active record only'),
        ),
    ]
